'use client';

import type React from 'react';
import {
  Activity,
  AirVent,
  AlarmClock,
  Ambulance,
  Anchor,
  Aperture,
  Armchair,
  Award,
  Briefcase,
  Building2,
  Building,
  CalendarCheck2,
  Camera,
  ChartColumn,
  Check,
  ChefHat,
  Clock,
  Cog,
  Compass,
  Crosshair,
  Cpu,
  Crown,
  Diamond,
  FileCheck2,
  FileText,
  Fingerprint,
  Flag,
  Flame,
  Gem,
  Globe,
  HandCoins,
  HeartHandshake,
  Home,
  KeyRound,
  Layers,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessagesSquare,
  MonitorSmartphone,
  Package,
  Palette,
  PenTool,
  Phone,
  Receipt,
  Rocket,
  ScanSearch,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Target,
  Trophy,
  Truck,
  UserCheck,
  Users,
  WandSparkles,
  Wrench,
  Zap,
} from 'lucide-react';

export const ABOUT_ICON_NAMES = [
  'Activity', 'AirVent', 'AlarmClock', 'Ambulance', 'Anchor', 'Aperture', 'Armchair', 'Award',
  'Briefcase', 'Building', 'Building2', 'CalendarCheck2', 'Camera', 'ChartColumn', 'Check', 'ChefHat',
  'Clock', 'Cog', 'Compass', 'Crosshair', 'Cpu', 'Crown', 'Diamond', 'FileCheck2', 'FileText',
  'Fingerprint', 'Flag', 'Flame', 'Gem', 'Globe', 'HandCoins', 'HeartHandshake', 'Home', 'KeyRound',
  'Layers', 'Leaf', 'LifeBuoy', 'Lightbulb', 'Lock', 'Mail', 'MapPin', 'Megaphone', 'MessagesSquare',
  'MonitorSmartphone', 'Package', 'Palette', 'PenTool', 'Phone', 'Receipt', 'Rocket', 'ScanSearch',
  'Search', 'Send', 'Server', 'Settings', 'Shield', 'ShieldCheck', 'ShoppingBag', 'Smartphone',
  'Sparkles', 'Star', 'Stethoscope', 'Store', 'Target', 'Trophy', 'Truck', 'UserCheck', 'Users',
  'WandSparkles', 'Wrench', 'Zap',
] as const;

export const ABOUT_ICON_COMPONENTS: Record<string, React.ComponentType<{ size?: number; className?: string; style?: React.CSSProperties }>> = {
  Activity,
  AirVent,
  AlarmClock,
  Ambulance,
  Anchor,
  Aperture,
  Armchair,
  Award,
  Briefcase,
  Building,
  Building2,
  CalendarCheck2,
  Camera,
  ChartColumn,
  Check,
  ChefHat,
  Clock,
  Cog,
  Compass,
  Crosshair,
  Cpu,
  Crown,
  Diamond,
  FileCheck2,
  FileText,
  Fingerprint,
  Flag,
  Flame,
  Gem,
  Globe,
  HandCoins,
  HeartHandshake,
  Home,
  KeyRound,
  Layers,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessagesSquare,
  MonitorSmartphone,
  Package,
  Palette,
  PenTool,
  Phone,
  Receipt,
  Rocket,
  ScanSearch,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Target,
  Trophy,
  Truck,
  UserCheck,
  Users,
  WandSparkles,
  Wrench,
  Zap,
};

export const ABOUT_ICON_OPTIONS = ABOUT_ICON_NAMES.map((icon) => ({
  label: icon,
  value: icon,
}));

export const getAboutIconComponent = (iconName?: string) => (
  ABOUT_ICON_COMPONENTS[iconName ?? ''] || Star
);

/** Options compatible with shared IconPopoverPicker */
export const ABOUT_POPOVER_OPTIONS = ABOUT_ICON_NAMES.map((name) => ({
  value: name,
  label: name,
  Icon: ABOUT_ICON_COMPONENTS[name] || Star,
}));
