import { DollarSign, Image, Tag, Box, Package, Layers, Download, FolderTree, FileText, Code, SquareStack } from 'lucide-react';
import { defineModuleWithRuntime } from '../define-module';
import { PRODUCT_IMAGE_ASPECT_RATIO_OPTIONS } from '../../products/image-aspect-ratio';
 
export const productsModule = defineModuleWithRuntime({
   key: 'products',
  name: 'Sản phẩm',
   description: 'Cấu hình sản phẩm và danh mục',
   icon: Package,
   color: 'orange',
  categoryModuleKey: 'productCategories',

   features: [
     { key: 'enableSalePrice', label: 'Giá khuyến mãi', icon: DollarSign, linkedField: 'salePrice' },
     { key: 'enableGallery', label: 'Thư viện ảnh', icon: Image, linkedField: 'images' },
     { key: 'enableSKU', label: 'Mã SKU', icon: Tag, linkedField: 'sku', enabled: false },
    { key: 'enableBarcode', label: 'Mã vạch phiên bản', icon: Tag, linkedField: 'barcode', enabled: false },
     { key: 'enableStock', label: 'Quản lý kho', icon: Box, linkedField: 'stock' },
     { key: 'enableMarkdownRender', label: 'Markdown render', icon: FileText, linkedField: 'markdownRender', enabled: false },
     { key: 'enableHtmlRender', label: 'HTML render', icon: Code, linkedField: 'htmlRender', enabled: false },
     {
       key: 'enableCategoryHierarchy',
       label: 'Danh mục cha - con',
       description: 'Cho phép phân cấp danh mục nhiều tầng',
       icon: FolderTree,
       linkedField: 'parentId',
      enabled: false,
     },
   ],

   settings: [
    { key: 'productsPerPage', label: 'Số SP / trang', type: 'number', default: 12 },
    {
      key: 'defaultStatus',
      label: 'Trạng thái mặc định',
      type: 'select',
      default: 'Draft',
      options: [
        { value: 'Draft', label: 'Bản nháp' },
        { value: 'Active', label: 'Đang bán' },
      ],
    },
    {
      key: 'enableMultipleCategories',
      label: 'Cho phép nhiều danh mục',
      type: 'toggle',
      default: false,
    },
    {
      key: 'saleMode',
      label: 'Chế độ bán hàng',
      type: 'select',
      default: 'cart',
      options: [
        { value: 'cart', label: 'Giỏ hàng & thanh toán' },
        { value: 'contact', label: 'Nút liên hệ (/contact)' },
        { value: 'affiliate', label: 'Nút Affiliate (Mua ngay)' },
      ],
    },
    {
      key: 'enableExcelActions',
      label: 'Bật Import/Export Excel',
      type: 'toggle',
      default: true,
    },
    {
      key: 'defaultImageAspectRatio',
      label: 'Tỉ lệ ảnh sản phẩm mặc định',
      type: 'select',
      default: 'square',
      options: PRODUCT_IMAGE_ASPECT_RATIO_OPTIONS,
    },

    {
      key: 'enableImageCrop',
      label: 'Bật cắt ảnh theo tỉ lệ khi upload',
      type: 'toggle',
      default: false,
    },
    {
      key: 'enableProductWatermark',
      label: 'Bật watermark sản phẩm',
      type: 'toggle',
      default: false,
    },
    {
      key: 'enableProductSupplementalContent',
      label: 'Bật mẫu nội dung dùng chung cho sản phẩm',
      type: 'toggle',
      default: false,
      group: 'supplementalContent',
    },
    {
      key: 'showCategorySubtitle',
      label: 'Hiện mô tả dưới tên danh mục',
      type: 'toggle',
      default: false,
      group: 'categoryContent',
    },
    {
      key: 'enableCategoryFilterFooterContent',
      label: 'Hiện nội dung cuối trang danh mục',
      type: 'toggle',
      default: false,
      group: 'categoryContent',
    },
    {
      key: 'enableCategoryProductDetailSuffix',
      label: 'Nối nội dung danh mục vào chi tiết sản phẩm',
      type: 'toggle',
      default: false,
      group: 'categoryContent',
    },
    {
      key: 'enableCategoryProductDetailFaq',
      label: 'Hiện FAQ danh mục ở chi tiết sản phẩm',
      type: 'toggle',
      default: false,
      group: 'categoryContent',
    },

    { key: 'lowStockThreshold', label: 'Ngưỡng tồn kho thấp', type: 'number', default: 10 },
    {
      key: 'variantEnabled',
      label: 'Bật tính năng phiên bản',
      type: 'toggle',
      default: false,
      group: 'variants',
    },
    {
      key: 'variantPricing',
      label: 'Giá theo',
      type: 'select',
      default: 'variant',
      options: [
        { value: 'product', label: 'Sản phẩm (giá chung)' },
        { value: 'variant', label: 'Phiên bản (giá riêng)' },
      ],
      group: 'variants',
      dependsOn: 'variantEnabled',
    },
    {
      key: 'variantStock',
      label: 'Tồn kho theo',
      type: 'select',
      default: 'variant',
      options: [
        { value: 'product', label: 'Sản phẩm (tồn chung)' },
        { value: 'variant', label: 'Phiên bản (tồn riêng)' },
      ],
      group: 'variants',
      dependsOn: 'variantEnabled',
    },
    {
      key: 'variantImages',
      label: 'Ảnh phiên bản',
      type: 'select',
      default: 'inherit',
      options: [
        { value: 'inherit', label: 'Kế thừa từ sản phẩm' },
        { value: 'override', label: 'Ảnh riêng mỗi phiên bản' },
        { value: 'both', label: 'Cả hai (có thể override)' },
      ],
      group: 'variants',
      dependsOn: 'variantEnabled',
    },
    {
      key: 'outOfStockDisplay',
      label: 'Hiển thị hết hàng',
      type: 'select',
      default: 'blur',
      options: [
        { value: 'hide', label: 'Ẩn hoàn toàn' },
        { value: 'disable', label: 'Vô hiệu hóa + gạch ngang' },
        { value: 'blur', label: 'Mờ đi + Badge "Hết hàng"' },
      ],
      group: 'variants',
      dependsOn: 'variantEnabled',
    },
    {
      key: 'imageChangeAnimation',
      label: 'Hiệu ứng đổi ảnh',
      type: 'select',
      default: 'fade',
      options: [
        { value: 'none', label: 'Không có' },
        { value: 'fade', label: 'Fade (mờ dần)' },
        { value: 'slide', label: 'Slide (trượt)' },
      ],
      group: 'variants',
      dependsOn: 'variantEnabled',
    },
    {
      key: 'productTypeMode',
      label: 'Loại sản phẩm',
      type: 'select',
      default: 'both',
      options: [
        { value: 'physical', label: 'Vật lý' },
        { value: 'digital', label: 'Digital' },
        { value: 'both', label: 'Cả hai' },
      ],
      group: 'digital',
    },
    {
      key: 'defaultDigitalDeliveryType',
      label: 'Loại giao hàng mặc định',
      type: 'select',
      default: 'account',
      options: [
        { value: 'account', label: 'Tài khoản (username/password)' },
        { value: 'license', label: 'License Key' },
        { value: 'download', label: 'File Download' },
        { value: 'custom', label: 'Tùy chỉnh' },
      ],
      group: 'digital',
    },
    {
      key: 'enableCombos',
      label: 'Bật hệ thống Combo',
      type: 'toggle',
      default: false,
      group: 'general',
    },
    {
      key: 'enableProductTypes',
      label: 'Bật hệ thống Phân loại & Thuộc tính',
      type: 'toggle',
      default: false,
      group: 'general',
    },
   ],

   settingGroups: [
     { key: 'general', label: 'Cài đặt chung' },
     { key: 'categoryContent', label: 'Nội dung riêng theo Danh mục', icon: FolderTree },
     { key: 'supplementalContent', label: 'Nội dung mô tả dùng chung', icon: SquareStack },
     { key: 'variants', label: 'Phiên bản sản phẩm', icon: Layers },
     { key: 'digital', label: 'Sản phẩm Digital', icon: Download },
   ],

   conventionNote: 'Slug tự động từ tên. SKU phải unique. Trường price và status bắt buộc.',

  runtimeConfig: {
    fields: [
      { enabled: true, fieldKey: 'name', isSystem: true, name: 'Tên sản phẩm', order: 0, required: true, type: 'text' },
      { enabled: true, fieldKey: 'slug', isSystem: true, name: 'Slug', order: 1, required: true, type: 'text' },
      { enabled: false, fieldKey: 'sku', isSystem: false, linkedFeature: 'enableSKU', name: 'Mã SKU', order: 2, required: true, type: 'text' },
      { enabled: false, fieldKey: 'barcode', isSystem: false, linkedFeature: 'enableBarcode', name: 'Mã vạch phiên bản', order: 3, required: false, type: 'text' },
      { enabled: true, fieldKey: 'price', isSystem: true, name: 'Giá bán', order: 4, required: true, type: 'price' },
      { enabled: true, fieldKey: 'salePrice', isSystem: false, linkedFeature: 'enableSalePrice', name: 'Giá khuyến mãi', order: 5, required: false, type: 'price' },
      { enabled: true, fieldKey: 'stock', isSystem: false, linkedFeature: 'enableStock', name: 'Tồn kho', order: 6, required: false, type: 'number' },
      { enabled: true, fieldKey: 'status', isSystem: true, name: 'Trạng thái', order: 7, required: true, type: 'select' },
      { enabled: true, fieldKey: 'categoryId', isSystem: true, name: 'Danh mục', order: 8, required: true, type: 'select' },
      { enabled: true, fieldKey: 'description', isSystem: false, name: 'Mô tả', order: 9, required: false, type: 'richtext' },
      { enabled: true, fieldKey: 'image', isSystem: false, name: 'Ảnh đại diện', order: 10, required: false, type: 'image' },
      { enabled: true, fieldKey: 'images', isSystem: false, linkedFeature: 'enableGallery', name: 'Thư viện ảnh', order: 11, required: false, type: 'gallery' },
      { enabled: true, fieldKey: 'metaTitle', group: 'seo', isSystem: false, name: 'Meta Title', order: 12, required: false, type: 'text' },
      { enabled: true, fieldKey: 'metaDescription', group: 'seo', isSystem: false, name: 'Meta Description', order: 13, required: false, type: 'textarea' },
      { enabled: true, fieldKey: 'renderType', isSystem: false, name: 'Kiểu render', order: 14, required: false, type: 'select' },
      { enabled: false, fieldKey: 'markdownRender', isSystem: false, linkedFeature: 'enableMarkdownRender', name: 'Markdown render', order: 15, required: false, type: 'textarea' },
      { enabled: false, fieldKey: 'htmlRender', isSystem: false, linkedFeature: 'enableHtmlRender', name: 'HTML render', order: 16, required: false, type: 'textarea' },
    ],
  },

  tabs: ['config'],
});
