'use client';

import type { Id } from '@/convex/_generated/dataModel';
import type { CategoryConfigItem } from '../_types';

export type ProductCategoriesAutoGenerateCandidate = {
  categoryId: Id<'productCategories'>;
  name: string;
  image?: string;
  productCount: number;
  representativeImage?: string;
  representativeProductId: Id<'products'>;
  firstProductTime: number;
};

export type ProductCategoriesAutoGenerateResult =
  | { status: 'empty-source' }
  | { status: 'empty-result' }
  | { status: 'success'; items: CategoryConfigItem[] };

export function buildAutoGeneratedProductCategoriesItems(
  candidates: ProductCategoriesAutoGenerateCandidate[]
): ProductCategoriesAutoGenerateResult {
  if (candidates.length === 0) {
    return { status: 'empty-source' };
  }

  const items = candidates
    .filter((candidate) => candidate.productCount > 0 && candidate.representativeProductId && candidate.representativeImage)
    .map((candidate, index) => ({
      id: index + 1,
      categoryId: candidate.categoryId,
      customImage: `product:${candidate.representativeProductId}`,
      imageMode: 'product-image' as const,
    }));

  if (items.length === 0) {
    return { status: 'empty-result' };
  }

  return { status: 'success', items };
}
