'use client';

import { useQuery } from 'convex/react';
import { api } from '@/convex/_generated/api';
import { buildAutoGeneratedProductCategoriesItems } from './auto-generate';

export function useProductCategoriesAutoGenerate() {
  const payload = useQuery(api.productCategories.listActiveAutoFillCandidates, {
    productLimit: 5000,
  });

  const isAutoGenerateLoading = payload === undefined;
  const isAutoGenerateReady = payload !== undefined;

  const generateFromRealData = () => {
    if (!payload) {
      return { status: 'loading' as const };
    }

    return buildAutoGeneratedProductCategoriesItems(payload.categories);
  };

  return {
    autoGenerateCandidates: payload?.categories ?? [],
    isAutoGenerateLoading,
    isAutoGenerateReady,
    generateFromRealData,
  };
}
