export const COMPONENT_LAYOUTS: Record<string, string[]> = {
  Marquee: ['ribbon', 'gradient', 'minimal', 'dark', 'split', 'stripe'],
  About: ['classic', 'bento', 'minimal', 'split', 'timeline', 'showcase', 'spaCollage', 'solarFeature', 'kanban'],
  Benefits: ['1', '2', '3', '4', '5', '6'],
  Blog: ['layout1', 'layout2', 'layout3', 'layout4', 'layout5', 'layout6', 'layout7'],
  Career: ['cards', 'list', 'minimal', 'table', 'featured', 'timeline'],
  CaseStudy: ['grid', 'featured', 'list', 'masonry', 'carousel', 'timeline'],
  CategoryProducts: ['grid', 'carousel', 'cards', 'bento', 'magazine', 'showcase', 'wine-grid'],
  Clients: ['layout01', 'layout02', 'layout03', 'layout04', 'layout05', 'layout06', 'layout07', 'layout08'],
  Contact: ['modern', 'floating', 'grid', 'elegant', 'minimal', 'centered', 'kanban'],
  Countdown: ['banner', 'floating', 'minimal', 'split', 'sticky', 'popup'],
  CTA: ['banner', 'centered', 'split', 'floating', 'gradient', 'minimal'],
  FAQ: ['wine-list', 'accordion', 'minimal', 'timeline', 'cards', 'two-column', 'tabbed'],
  Footer: ['classic', 'modern', 'corporate', 'minimal', 'centered', 'stacked'],
  Gallery: ['spotlight', 'explore', 'stories', 'grid', 'marquee', 'masonry'],
  TrustBadges: ['grid', 'cards', 'stack', 'wall', 'carousel', 'seal'],
  Hero: ['slider', 'fade', 'builderCoffee', 'bento', 'triple', 'triple2', 'fullscreen', 'conquest', 'split', 'parallax'],
  HomepageCategoryHero: ['sidebar', 'classic', 'flush', 'minimal', 'soft', 'top-nav'],
  Partners: ['grid', 'marquee', 'badge', 'carousel', 'logoCloud', 'glassLogoCloud', 'clean', 'divider'],
  Popup: ['center-card', 'split-visual', 'bottom-sheet', 'side-panel', 'minimal-alert', 'full-screen', 'image-only', 'centered-advertisement'],
  Pricing: ['cards', 'horizontal', 'minimal', 'comparison', 'featured', 'compact', 'tabbed', 'construction'],
  ProductCategories: ['image-strip', 'carousel', 'cards', 'marquee', 'circular', 'icon-grid', 'mosaic', 'compact-grid', 'grid', 'grid-10', 'grid-11'],
  ProductGrid: ['commerce', 'minimal', 'compact', 'magazine', 'catalog', 'mosaic', 'tabbed', 'storefront'],
  ProductList: ['commerce', 'minimal', 'bento', 'carousel', 'wine-carousel', 'compact', 'showcase', 'lookbook'],
  ServiceList: ['grid', 'bento', 'list', 'carousel', 'minimal', 'showcase', 'kanban'],
  Services: ['elegantGrid', 'modernList', 'bigNumber', 'cards', 'carousel', 'timeline', 'builderPolicy', 'builderFeatureCircle'],
  SpeedDial: ['fab', 'sidebar', 'pills', 'stack', 'dock', 'minimal', 'builder-bar'],
  Stats: ['horizontal', 'cards', 'icons', 'gradient', 'minimal', 'counter', 'solar-hero', 'builder-overlay'],
  Team: ['grid', 'cards', 'carousel', 'bento', 'timeline', 'spotlight', 'construction', 'layout8'],
  Testimonials: ['cards', 'slider', 'marquee', 'showcase', 'quote', 'minimal', 'split-carousel', 'overlap-carousel', 'builder-cards', 'builder-carousel'],
  Video: ['centered', 'split', 'fullwidth', 'cinema', 'minimal', 'parallax'],
  VoucherPromotions: ['enterpriseCards', 'ticketHorizontal', 'imageTicket', 'couponGrid', 'stackedBanner', 'carousel', 'minimal']
};
