'use client';

import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Airplay,
  AlarmClock,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BadgeCheck,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  Bike,
  Book,
  Bookmark,
  Briefcase,
  Brush,
  Building,
  Calendar,
  Camera,
  Car,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Cog,
  Compass,
  Copy,
  CreditCard,
  Crown,
  Database,
  Download,
  Droplets,
  Edit3,
  Eye,
  FileText,
  Filter,
  Flag,
  Folder,
  Gift,
  Globe,
  Grid3X3,
  Heart,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Inbox,
  Info,
  KeyRound,
  Layers,
  Leaf,
  Link,
  List,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Music,
  Package,
  Palette,
  Paperclip,
  PenSquare,
  Phone,
  PieChart,
  Pin,
  Play,
  Plus,
  QrCode,
  Rocket,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Tag,
  ThumbsUp,
  Ticket,
  Trash2,
  TrendingUp,
  Trophy,
  Truck,
  Upload,
  User,
  Users,
  Video,
  Wand2,
  Wifi,
  Zap,
} from 'lucide-react';

export type HomepageCategoryHeroIconOption = {
  name: string;
  label: string;
  Icon: LucideIcon;
};

export const HOMEPAGE_CATEGORY_HERO_ICON_OPTIONS: HomepageCategoryHeroIconOption[] = [
  { name: 'Activity', label: 'Activity', Icon: Activity },
  { name: 'Airplay', label: 'Airplay', Icon: Airplay },
  { name: 'AlarmClock', label: 'Alarm Clock', Icon: AlarmClock },
  { name: 'AlignCenter', label: 'Align Center', Icon: AlignCenter },
  { name: 'AlignJustify', label: 'Align Justify', Icon: AlignJustify },
  { name: 'AlignLeft', label: 'Align Left', Icon: AlignLeft },
  { name: 'AlignRight', label: 'Align Right', Icon: AlignRight },
  { name: 'Archive', label: 'Archive', Icon: Archive },
  { name: 'ArrowDown', label: 'Arrow Down', Icon: ArrowDown },
  { name: 'ArrowLeft', label: 'Arrow Left', Icon: ArrowLeft },
  { name: 'ArrowRight', label: 'Arrow Right', Icon: ArrowRight },
  { name: 'ArrowUp', label: 'Arrow Up', Icon: ArrowUp },
  { name: 'Award', label: 'Award', Icon: Award },
  { name: 'BadgeCheck', label: 'Badge Check', Icon: BadgeCheck },
  { name: 'Ban', label: 'Ban', Icon: Ban },
  { name: 'Banknote', label: 'Banknote', Icon: Banknote },
  { name: 'BarChart3', label: 'Bar Chart', Icon: BarChart3 },
  { name: 'Bell', label: 'Bell', Icon: Bell },
  { name: 'Bike', label: 'Bike', Icon: Bike },
  { name: 'Book', label: 'Book', Icon: Book },
  { name: 'Bookmark', label: 'Bookmark', Icon: Bookmark },
  { name: 'Briefcase', label: 'Briefcase', Icon: Briefcase },
  { name: 'Brush', label: 'Brush', Icon: Brush },
  { name: 'Building', label: 'Building', Icon: Building },
  { name: 'Calendar', label: 'Calendar', Icon: Calendar },
  { name: 'Camera', label: 'Camera', Icon: Camera },
  { name: 'Car', label: 'Car', Icon: Car },
  { name: 'Check', label: 'Check', Icon: Check },
  { name: 'CheckCircle2', label: 'Check Circle', Icon: CheckCircle2 },
  { name: 'ChevronDown', label: 'Chevron Down', Icon: ChevronDown },
  { name: 'ChevronLeft', label: 'Chevron Left', Icon: ChevronLeft },
  { name: 'ChevronRight', label: 'Chevron Right', Icon: ChevronRight },
  { name: 'ChevronUp', label: 'Chevron Up', Icon: ChevronUp },
  { name: 'ClipboardList', label: 'Clipboard List', Icon: ClipboardList },
  { name: 'Clock', label: 'Clock', Icon: Clock },
  { name: 'Cloud', label: 'Cloud', Icon: Cloud },
  { name: 'Code', label: 'Code', Icon: Code },
  { name: 'Cog', label: 'Cog', Icon: Cog },
  { name: 'Compass', label: 'Compass', Icon: Compass },
  { name: 'Copy', label: 'Copy', Icon: Copy },
  { name: 'CreditCard', label: 'Credit Card', Icon: CreditCard },
  { name: 'Crown', label: 'Crown', Icon: Crown },
  { name: 'Database', label: 'Database', Icon: Database },
  { name: 'Download', label: 'Download', Icon: Download },
  { name: 'Droplets', label: 'Droplets', Icon: Droplets },
  { name: 'Edit3', label: 'Edit', Icon: Edit3 },
  { name: 'Eye', label: 'Eye', Icon: Eye },
  { name: 'FileText', label: 'File Text', Icon: FileText },
  { name: 'Filter', label: 'Filter', Icon: Filter },
  { name: 'Flag', label: 'Flag', Icon: Flag },
  { name: 'Folder', label: 'Folder', Icon: Folder },
  { name: 'Gift', label: 'Gift', Icon: Gift },
  { name: 'Globe', label: 'Globe', Icon: Globe },
  { name: 'Grid3X3', label: 'Grid', Icon: Grid3X3 },
  { name: 'Heart', label: 'Heart', Icon: Heart },
  { name: 'HelpCircle', label: 'Help Circle', Icon: HelpCircle },
  { name: 'Home', label: 'Home', Icon: Home },
  { name: 'Image', label: 'Image', Icon: ImageIcon },
  { name: 'Inbox', label: 'Inbox', Icon: Inbox },
  { name: 'Info', label: 'Info', Icon: Info },
  { name: 'KeyRound', label: 'Key', Icon: KeyRound },
  { name: 'Layers', label: 'Layers', Icon: Layers },
  { name: 'Leaf', label: 'Leaf', Icon: Leaf },
  { name: 'Link', label: 'Link', Icon: Link },
  { name: 'List', label: 'List', Icon: List },
  { name: 'Lock', label: 'Lock', Icon: Lock },
  { name: 'Mail', label: 'Mail', Icon: Mail },
  { name: 'MapPin', label: 'Map Pin', Icon: MapPin },
  { name: 'Menu', label: 'Menu', Icon: Menu },
  { name: 'MessageCircle', label: 'Message', Icon: MessageCircle },
  { name: 'Mic', label: 'Mic', Icon: Mic },
  { name: 'Monitor', label: 'Monitor', Icon: Monitor },
  { name: 'Moon', label: 'Moon', Icon: Moon },
  { name: 'Music', label: 'Music', Icon: Music },
  { name: 'Package', label: 'Package', Icon: Package },
  { name: 'Palette', label: 'Palette', Icon: Palette },
  { name: 'Paperclip', label: 'Paperclip', Icon: Paperclip },
  { name: 'PenSquare', label: 'Pen Square', Icon: PenSquare },
  { name: 'Phone', label: 'Phone', Icon: Phone },
  { name: 'PieChart', label: 'Pie Chart', Icon: PieChart },
  { name: 'Pin', label: 'Pin', Icon: Pin },
  { name: 'Play', label: 'Play', Icon: Play },
  { name: 'Plus', label: 'Plus', Icon: Plus },
  { name: 'QrCode', label: 'QR Code', Icon: QrCode },
  { name: 'Rocket', label: 'Rocket', Icon: Rocket },
  { name: 'Search', label: 'Search', Icon: Search },
  { name: 'Send', label: 'Send', Icon: Send },
  { name: 'Settings', label: 'Settings', Icon: Settings },
  { name: 'Shield', label: 'Shield', Icon: Shield },
  { name: 'ShoppingBag', label: 'Shopping Bag', Icon: ShoppingBag },
  { name: 'ShoppingCart', label: 'Shopping Cart', Icon: ShoppingCart },
  { name: 'SlidersHorizontal', label: 'Sliders', Icon: SlidersHorizontal },
  { name: 'Smartphone', label: 'Smartphone', Icon: Smartphone },
  { name: 'Sparkles', label: 'Sparkles', Icon: Sparkles },
  { name: 'Star', label: 'Star', Icon: Star },
  { name: 'Sun', label: 'Sun', Icon: Sun },
  { name: 'Tag', label: 'Tag', Icon: Tag },
  { name: 'ThumbsUp', label: 'Thumbs Up', Icon: ThumbsUp },
  { name: 'Ticket', label: 'Ticket', Icon: Ticket },
  { name: 'Trash2', label: 'Trash', Icon: Trash2 },
  { name: 'TrendingUp', label: 'Trending Up', Icon: TrendingUp },
  { name: 'Trophy', label: 'Trophy', Icon: Trophy },
  { name: 'Truck', label: 'Truck', Icon: Truck },
  { name: 'Upload', label: 'Upload', Icon: Upload },
  { name: 'User', label: 'User', Icon: User },
  { name: 'Users', label: 'Users', Icon: Users },
  { name: 'Video', label: 'Video', Icon: Video },
  { name: 'Wand2', label: 'Wand', Icon: Wand2 },
  { name: 'Wifi', label: 'Wifi', Icon: Wifi },
  { name: 'Zap', label: 'Zap', Icon: Zap },
];

export const HOMEPAGE_CATEGORY_HERO_ICON_MAP = HOMEPAGE_CATEGORY_HERO_ICON_OPTIONS.reduce<Record<string, LucideIcon>>(
  (acc, option) => {
    acc[option.name] = option.Icon;
    return acc;
  },
  {}
);

export const getHomepageCategoryHeroIcon = (name?: string): LucideIcon | undefined => {
  if (!name) {return undefined;}
  return HOMEPAGE_CATEGORY_HERO_ICON_MAP[name];
};
