'use client';

import { createElement } from 'react';
import type { ComponentType, ReactNode } from 'react';
import {
  Activity,
  Airplay,
  AlertCircle,
  AlertTriangle,
  Anchor,
  Aperture,
  Archive,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  Award,
  BadgeCheck,
  Banknote,
  Bell,
  BellRing,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Check,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Compass,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  Facebook,
  FileImage,
  FileText,
  Flag,
  Folder,
  Gift,
  Globe,
  Handshake,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Info,
  Instagram,
  Key,
  Landmark,
  LayoutGrid,
  Link,
  Linkedin,
  Mail,
  Map,
  MapPin,
  MapPinned,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Phone,
  PhoneCall,
  PieChart,
  Pin,
  Printer,
  QrCode,
  Rocket,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  Shield,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  ThumbsUp,
  Ticket,
  TrendingUp,
  Truck,
  Twitter,
  User,
  Users,
  Video,
  Wallet,
  Wifi,
  Wrench,
  Youtube,
  Zap,
} from 'lucide-react';

export type ContactIconOption = {
  value: string;
  label: string;
  Icon: ComponentType<{ size?: number; className?: string }>;
};

export const CONTACT_ICON_OPTIONS: ContactIconOption[] = [
  { value: 'activity', label: 'Activity', Icon: Activity },
  { value: 'airplay', label: 'Airplay', Icon: Airplay },
  { value: 'alert-circle', label: 'Alert Circle', Icon: AlertCircle },
  { value: 'alert-triangle', label: 'Alert Triangle', Icon: AlertTriangle },
  { value: 'anchor', label: 'Anchor', Icon: Anchor },
  { value: 'aperture', label: 'Aperture', Icon: Aperture },
  { value: 'archive', label: 'Archive', Icon: Archive },
  { value: 'arrow-right', label: 'Arrow Right', Icon: ArrowRight },
  { value: 'arrow-up-right', label: 'Arrow Up Right', Icon: ArrowUpRight },
  { value: 'at-sign', label: 'At Sign', Icon: AtSign },
  { value: 'award', label: 'Award', Icon: Award },
  { value: 'badge-check', label: 'Badge Check', Icon: BadgeCheck },
  { value: 'banknote', label: 'Banknote', Icon: Banknote },
  { value: 'bell', label: 'Bell', Icon: Bell },
  { value: 'bell-ring', label: 'Bell Ring', Icon: BellRing },
  { value: 'bike', label: 'Bike', Icon: Bike },
  { value: 'book-open', label: 'Book Open', Icon: BookOpen },
  { value: 'briefcase', label: 'Briefcase', Icon: Briefcase },
  { value: 'building-2', label: 'Building', Icon: Building2 },
  { value: 'calendar', label: 'Calendar', Icon: Calendar },
  { value: 'camera', label: 'Camera', Icon: Camera },
  { value: 'check', label: 'Check', Icon: Check },
  { value: 'clipboard', label: 'Clipboard', Icon: Clipboard },
  { value: 'clipboard-list', label: 'Clipboard List', Icon: ClipboardList },
  { value: 'clock', label: 'Clock', Icon: Clock },
  { value: 'cloud', label: 'Cloud', Icon: Cloud },
  { value: 'code', label: 'Code', Icon: Code },
  { value: 'compass', label: 'Compass', Icon: Compass },
  { value: 'cpu', label: 'CPU', Icon: Cpu },
  { value: 'credit-card', label: 'Credit Card', Icon: CreditCard },
  { value: 'database', label: 'Database', Icon: Database },
  { value: 'dollar-sign', label: 'Dollar Sign', Icon: DollarSign },
  { value: 'download', label: 'Download', Icon: Download },
  { value: 'edit', label: 'Edit', Icon: Edit },
  { value: 'external-link', label: 'External Link', Icon: ExternalLink },
  { value: 'eye', label: 'Eye', Icon: Eye },
  { value: 'facebook', label: 'Facebook', Icon: Facebook },
  { value: 'file-image', label: 'File Image', Icon: FileImage },
  { value: 'file-text', label: 'File Text', Icon: FileText },
  { value: 'flag', label: 'Flag', Icon: Flag },
  { value: 'folder', label: 'Folder', Icon: Folder },
  { value: 'gift', label: 'Gift', Icon: Gift },
  { value: 'globe', label: 'Globe', Icon: Globe },
  { value: 'handshake', label: 'Handshake', Icon: Handshake },
  { value: 'headphones', label: 'Headphones', Icon: Headphones },
  { value: 'heart', label: 'Heart', Icon: Heart },
  { value: 'help-circle', label: 'Help Circle', Icon: HelpCircle },
  { value: 'home', label: 'Home', Icon: Home },
  { value: 'image', label: 'Image', Icon: Image },
  { value: 'inbox', label: 'Inbox', Icon: Inbox },
  { value: 'info', label: 'Info', Icon: Info },
  { value: 'instagram', label: 'Instagram', Icon: Instagram },
  { value: 'key', label: 'Key', Icon: Key },
  { value: 'landmark', label: 'Landmark', Icon: Landmark },
  { value: 'layout-grid', label: 'Layout Grid', Icon: LayoutGrid },
  { value: 'link', label: 'Link', Icon: Link },
  { value: 'linkedin', label: 'LinkedIn', Icon: Linkedin },
  { value: 'mail', label: 'Mail', Icon: Mail },
  { value: 'map', label: 'Map', Icon: Map },
  { value: 'map-pin', label: 'Map Pin', Icon: MapPin },
  { value: 'map-pinned', label: 'Map Pinned', Icon: MapPinned },
  { value: 'message-circle', label: 'Message Circle', Icon: MessageCircle },
  { value: 'message-square', label: 'Message Square', Icon: MessageSquare },
  { value: 'mic', label: 'Mic', Icon: Mic },
  { value: 'monitor', label: 'Monitor', Icon: Monitor },
  { value: 'moon', label: 'Moon', Icon: Moon },
  { value: 'phone', label: 'Phone', Icon: Phone },
  { value: 'phone-call', label: 'Phone Call', Icon: PhoneCall },
  { value: 'pie-chart', label: 'Pie Chart', Icon: PieChart },
  { value: 'pin', label: 'Pin', Icon: Pin },
  { value: 'printer', label: 'Printer', Icon: Printer },
  { value: 'qr-code', label: 'QR Code', Icon: QrCode },
  { value: 'rocket', label: 'Rocket', Icon: Rocket },
  { value: 'search', label: 'Search', Icon: Search },
  { value: 'send', label: 'Send', Icon: Send },
  { value: 'settings', label: 'Settings', Icon: Settings },
  { value: 'share-2', label: 'Share', Icon: Share2 },
  { value: 'shield-check', label: 'Shield Check', Icon: ShieldCheck },
  { value: 'shield', label: 'Shield', Icon: Shield },
  { value: 'shopping-bag', label: 'Shopping Bag', Icon: ShoppingBag },
  { value: 'smartphone', label: 'Smartphone', Icon: Smartphone },
  { value: 'sparkles', label: 'Sparkles', Icon: Sparkles },
  { value: 'star', label: 'Star', Icon: Star },
  { value: 'store', label: 'Store', Icon: Store },
  { value: 'sun', label: 'Sun', Icon: Sun },
  { value: 'tag', label: 'Tag', Icon: Tag },
  { value: 'target', label: 'Target', Icon: Target },
  { value: 'thumbs-up', label: 'Thumbs Up', Icon: ThumbsUp },
  { value: 'ticket', label: 'Ticket', Icon: Ticket },
  { value: 'trending-up', label: 'Trending Up', Icon: TrendingUp },
  { value: 'truck', label: 'Truck', Icon: Truck },
  { value: 'twitter', label: 'Twitter', Icon: Twitter },
  { value: 'user', label: 'User', Icon: User },
  { value: 'users', label: 'Users', Icon: Users },
  { value: 'video', label: 'Video', Icon: Video },
  { value: 'wallet', label: 'Wallet', Icon: Wallet },
  { value: 'wifi', label: 'Wifi', Icon: Wifi },
  { value: 'wrench', label: 'Wrench', Icon: Wrench },
  { value: 'youtube', label: 'Youtube', Icon: Youtube },
  { value: 'zap', label: 'Zap', Icon: Zap },
];

const CONTACT_ICON_MAP = CONTACT_ICON_OPTIONS.reduce<Record<string, ContactIconOption['Icon']>>((acc, option) => {
  acc[option.value] = option.Icon;
  return acc;
}, {});

const LEGACY_ICON_ALIASES: Record<string, string> = {
  address: 'map-pin',
  'circle-help': 'help-circle',
  'contact-address': 'map-pin',
  'contact-email': 'mail',
  'contact-phone': 'phone',
  email: 'mail',
  help: 'help-circle',
  location: 'map-pin',
  telephone: 'phone',
  time: 'clock',
  'work-hours': 'clock',
  'working-hours': 'clock',
};

export const normalizeContactIconValue = (value: string): string => {
  const normalized = value
    .trim()
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();

  return LEGACY_ICON_ALIASES[normalized] ?? normalized;
};

export const resolveContactIcon = (value: string): ContactIconOption['Icon'] => {
  return CONTACT_ICON_MAP[value] ?? CONTACT_ICON_MAP[normalizeContactIconValue(value)] ?? HelpCircle;
};

export const renderContactIcon = (value: string, size = 16, className?: string): ReactNode => {
  const Icon = resolveContactIcon(value);
  return createElement(Icon, { size, className });
};
