'use client';

export type GuideArticle = {
  chapter: string;
  chapterOrder: number;
  description: string;
  keywords: string[];
  relatedRoutes: string[];
  section: string;
  sectionOrder: number;
  slug: string;
  subsection: string;
  subsectionOrder: number;
  title: string;
};

const createGuide = (guide: GuideArticle) => guide;

export const guideArticles = [
  createGuide({
    chapter: 'System Core',
    chapterOrder: 1,
    section: 'Điều hướng & nền',
    sectionOrder: 1,
    subsection: 'Khởi tạo hệ thống',
    subsectionOrder: 1,
    slug: 'system-overview-dashboard',
    title: 'Tổng quan dashboard system',
    description: 'Khung đọc nhanh trang gốc /system và vai trò từng khu điều hướng chính.',
    keywords: ['system', 'dashboard', 'tổng quan', 'sidebar'],
    relatedRoutes: ['/system'],
  }),
  createGuide({
    chapter: 'System Core',
    chapterOrder: 1,
    section: 'Điều hướng & nền',
    sectionOrder: 1,
    subsection: 'IA & định tuyến',
    subsectionOrder: 2,
    slug: 'system-ia-routing',
    title: 'IA và routing hệ thống',
    description: 'Khung hướng dẫn cách hiểu cấu trúc route và mối liên hệ giữa system, admin và site.',
    keywords: ['ia', 'routing', 'định tuyến', 'system'],
    relatedRoutes: ['/system/ia'],
  }),
  createGuide({
    chapter: 'System Core',
    chapterOrder: 1,
    section: 'Điều hướng & nền',
    sectionOrder: 1,
    subsection: 'Modules',
    subsectionOrder: 3,
    slug: 'system-module-management',
    title: 'Quản lý modules hệ thống',
    description: 'Khung đề mục để hiểu bật tắt module, phụ thuộc và ảnh hưởng liên đới.',
    keywords: ['module', 'modules', 'quản lý module', 'dependency'],
    relatedRoutes: ['/system/modules'],
  }),
  createGuide({
    chapter: 'System Core',
    chapterOrder: 1,
    section: 'Điều hướng & nền',
    sectionOrder: 1,
    subsection: 'Home Components',
    subsectionOrder: 4,
    slug: 'system-home-components-overview',
    title: 'Tổng quan home components',
    description: 'Khung đọc nhanh toàn bộ nhóm home components và cách chúng nối với preview/site.',
    keywords: ['home components', 'homepage', 'preview'],
    relatedRoutes: ['/system/home-components'],
  }),
  createGuide({
    chapter: 'System Core',
    chapterOrder: 1,
    section: 'Điều hướng & nền',
    sectionOrder: 1,
    subsection: 'Experiences',
    subsectionOrder: 5,
    slug: 'system-experiences-overview',
    title: 'Tổng quan experiences',
    description: 'Khung hiểu các experience pages và cách map với giao diện thật.',
    keywords: ['experiences', 'preview', 'layout'],
    relatedRoutes: ['/system/experiences'],
  }),
  createGuide({
    chapter: 'System Core',
    chapterOrder: 1,
    section: 'Vận hành hệ thống',
    sectionOrder: 2,
    subsection: 'Dữ liệu',
    subsectionOrder: 1,
    slug: 'system-data-manager',
    title: 'Data manager và thao tác dữ liệu',
    description: 'Khung điều hướng các điểm sửa dữ liệu, import/export và migration bundle.',
    keywords: ['data manager', 'data', 'migration', 'import', 'export'],
    relatedRoutes: ['/system/data'],
  }),
  createGuide({
    chapter: 'System Core',
    chapterOrder: 1,
    section: 'Vận hành hệ thống',
    sectionOrder: 2,
    subsection: 'Tích hợp',
    subsectionOrder: 2,
    slug: 'system-integrations',
    title: 'Tích hợp SMTP và cấu hình ngoài',
    description: 'Khung tìm hiểu integrations và các cấu hình kết nối hệ thống.',
    keywords: ['smtp', 'integration', 'tích hợp'],
    relatedRoutes: ['/system/integrations'],
  }),
  createGuide({
    chapter: 'System Core',
    chapterOrder: 1,
    section: 'Vận hành hệ thống',
    sectionOrder: 2,
    subsection: 'SEO',
    subsectionOrder: 3,
    slug: 'system-seo-discovery',
    title: 'SEO và discovery',
    description: 'Khung các màn cấu hình SEO, site verification và guided actions.',
    keywords: ['seo', 'discovery', 'site verification'],
    relatedRoutes: ['/system/seo'],
  }),
  createGuide({
    chapter: 'System Core',
    chapterOrder: 1,
    section: 'Vận hành hệ thống',
    sectionOrder: 2,
    subsection: 'SuperAdmin',
    subsectionOrder: 4,
    slug: 'system-superadmin-config',
    title: 'SuperAdmin và admin config',
    description: 'Khung các điểm cấu hình cấp cao trong khu /system/admin-config.',
    keywords: ['superadmin', 'admin config'],
    relatedRoutes: ['/system/admin-config'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Nội dung',
    sectionOrder: 1,
    subsection: 'Posts',
    subsectionOrder: 1,
    slug: 'admin-posts-management',
    title: 'Quản lý bài viết',
    description: 'Khung đề mục cho danh sách bài viết, tạo mới, sửa bài và category liên quan.',
    keywords: ['posts', 'bài viết', 'post categories'],
    relatedRoutes: ['/admin/posts', '/admin/posts/create', '/admin/post-categories'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Nội dung',
    sectionOrder: 1,
    subsection: 'Comments',
    subsectionOrder: 2,
    slug: 'admin-comments-management',
    title: 'Quản lý bình luận',
    description: 'Khung cho comment list, tạo mới và chỉnh sửa comment trong admin.',
    keywords: ['comments', 'bình luận'],
    relatedRoutes: ['/admin/comments', '/admin/comments/create'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Thương mại',
    sectionOrder: 2,
    subsection: 'Products',
    subsectionOrder: 1,
    slug: 'admin-products-management',
    title: 'Quản lý sản phẩm',
    description: 'Khung sản phẩm gồm list, create, edit, variants, options và supplemental settings.',
    keywords: ['products', 'sản phẩm', 'variants', 'product options'],
    relatedRoutes: ['/admin/products', '/admin/products/create', '/admin/product-options', '/admin/product-categories'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Thương mại',
    sectionOrder: 2,
    subsection: 'Orders',
    subsectionOrder: 2,
    slug: 'admin-orders-management',
    title: 'Quản lý đơn hàng',
    description: 'Khung đề mục cho list đơn hàng, tạo mới và chỉnh sửa order.',
    keywords: ['orders', 'đơn hàng'],
    relatedRoutes: ['/admin/orders', '/admin/orders/create'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Thương mại',
    sectionOrder: 2,
    subsection: 'Promotions',
    subsectionOrder: 3,
    slug: 'admin-promotions-management',
    title: 'Quản lý khuyến mãi',
    description: 'Khung list, create, edit promotion và điểm liên kết với promotions list experience.',
    keywords: ['promotions', 'khuyến mãi', 'voucher'],
    relatedRoutes: ['/admin/promotions', '/admin/promotions/create'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Thương mại',
    sectionOrder: 2,
    subsection: 'Cart & Wishlist',
    subsectionOrder: 4,
    slug: 'admin-cart-wishlist',
    title: 'Giỏ hàng và wishlist',
    description: 'Khung các màn cart, wishlist và mối liên hệ với trải nghiệm mua hàng.',
    keywords: ['cart', 'wishlist', 'giỏ hàng'],
    relatedRoutes: ['/admin/cart', '/admin/wishlist'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Dịch vụ & booking',
    sectionOrder: 3,
    subsection: 'Services',
    subsectionOrder: 1,
    slug: 'admin-services-management',
    title: 'Quản lý dịch vụ',
    description: 'Khung services list, create, edit và service categories.',
    keywords: ['services', 'dịch vụ', 'service categories'],
    relatedRoutes: ['/admin/services', '/admin/services/create', '/admin/service-categories'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Dịch vụ & booking',
    sectionOrder: 3,
    subsection: 'Bookings',
    subsectionOrder: 2,
    slug: 'admin-bookings-management',
    title: 'Quản lý bookings',
    description: 'Khung theo dõi đặt lịch, settings booking và flow public booking.',
    keywords: ['bookings', 'đặt lịch'],
    relatedRoutes: ['/admin/bookings', '/admin/bookings/settings'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Khách hàng & hệ thống',
    sectionOrder: 4,
    subsection: 'Customers',
    subsectionOrder: 1,
    slug: 'admin-customers-management',
    title: 'Quản lý khách hàng',
    description: 'Khung quản trị customer list, create và chỉnh sửa hồ sơ khách hàng.',
    keywords: ['customers', 'khách hàng'],
    relatedRoutes: ['/admin/customers', '/admin/customers/create'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Khách hàng & hệ thống',
    sectionOrder: 4,
    subsection: 'Users & Roles',
    subsectionOrder: 2,
    slug: 'admin-users-roles',
    title: 'Người dùng và phân quyền',
    description: 'Khung users, roles và các màn tạo/sửa phân quyền trong admin.',
    keywords: ['users', 'roles', 'phân quyền'],
    relatedRoutes: ['/admin/users', '/admin/users/create', '/admin/roles', '/admin/roles/create'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Khách hàng & hệ thống',
    sectionOrder: 4,
    subsection: 'Notifications',
    subsectionOrder: 3,
    slug: 'admin-notifications',
    title: 'Thông báo hệ thống',
    description: 'Khung list, create và edit notification trong admin.',
    keywords: ['notifications', 'thông báo'],
    relatedRoutes: ['/admin/notifications', '/admin/notifications/create'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Khách hàng & hệ thống',
    sectionOrder: 4,
    subsection: 'Media',
    subsectionOrder: 4,
    slug: 'admin-media-library',
    title: 'Thư viện media',
    description: 'Khung quản lý media list, chỉnh sửa media và điểm dùng chung toàn hệ thống.',
    keywords: ['media', 'thư viện media'],
    relatedRoutes: ['/admin/media'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Khách hàng & hệ thống',
    sectionOrder: 4,
    subsection: 'Menus',
    subsectionOrder: 5,
    slug: 'admin-menus-builder',
    title: 'Menu builder',
    description: 'Khung menu header, tầng lồng, quick picker và preview điều hướng.',
    keywords: ['menus', 'menu builder', 'header menu'],
    relatedRoutes: ['/admin/menus'],
  }),
  createGuide({
    chapter: 'Admin Modules',
    chapterOrder: 2,
    section: 'Khách hàng & hệ thống',
    sectionOrder: 4,
    subsection: 'Settings',
    subsectionOrder: 6,
    slug: 'admin-settings',
    title: 'Settings tổng',
    description: 'Khung settings general, contact, SEO, product frames và supplemental content.',
    keywords: ['settings', 'general', 'seo', 'contact'],
    relatedRoutes: ['/admin/settings', '/admin/settings/general', '/admin/settings/contact', '/admin/settings/seo'],
  }),
  createGuide({
    chapter: 'Home Components',
    chapterOrder: 3,
    section: 'Quản lý chung',
    sectionOrder: 1,
    subsection: 'Danh sách & tạo mới',
    subsectionOrder: 1,
    slug: 'admin-home-components-overview',
    title: 'Tổng quan home components admin',
    description: 'Khung list/create home components và cách điều hướng đến editor từng loại.',
    keywords: ['home components', 'create home component'],
    relatedRoutes: ['/admin/home-components', '/admin/home-components/create'],
  }),
  createGuide({
    chapter: 'Home Components',
    chapterOrder: 3,
    section: 'Quản lý chung',
    sectionOrder: 1,
    subsection: 'Smart Wizard',
    subsectionOrder: 2,
    slug: 'admin-home-components-smart-wizard-toggle',
    title: 'Bật/tắt Smart Wizard và xử lý khi nút không hiện',
    description: 'Hướng dẫn đầy đủ để kiểm tra setting enableSmartWizard, điều kiện hiển thị và checklist troubleshooting.',
    keywords: ['smart wizard', 'enableSmartWizard', 'home-components', 'wizard', 'troubleshooting'],
    relatedRoutes: ['/admin/home-components', '/system/huong-dan/admin-home-components-smart-wizard-toggle'],
  }),
  createGuide({
    chapter: 'Home Components',
    chapterOrder: 3,
    section: 'Quản lý chung',
    sectionOrder: 1,
    subsection: 'Homepage',
    subsectionOrder: 3,
    slug: 'admin-homepage-management',
    title: 'Quản lý homepage',
    description: 'Khung homepage list, create và edit để nối component vào trang chủ.',
    keywords: ['homepage', 'trang chủ'],
    relatedRoutes: ['/admin/homepage', '/admin/homepage/create'],
  }),
  createGuide({
    chapter: 'Home Components',
    chapterOrder: 3,
    section: 'Component theo loại',
    sectionOrder: 2,
    subsection: 'Hero & visual',
    subsectionOrder: 1,
    slug: 'admin-home-components-hero-visual',
    title: 'Hero, video, gallery và visual blocks',
    description: 'Khung nhóm component thiên về visual đầu trang và media-rich layout.',
    keywords: ['hero', 'video', 'gallery', 'visual'],
    relatedRoutes: ['/admin/home-components/create/hero', '/admin/home-components/create/video', '/admin/home-components/create/gallery'],
  }),
  createGuide({
    chapter: 'Home Components',
    chapterOrder: 3,
    section: 'Component theo loại',
    sectionOrder: 2,
    subsection: 'Trust badges',
    subsectionOrder: 2,
    slug: 'admin-home-components-trust-badges',
    title: 'Trust badges',
    description: 'Khung riêng cho component trust badges và các nút tạo/sửa liên quan.',
    keywords: ['trust badges', 'badge', 'uy tín'],
    relatedRoutes: ['/admin/home-components/create/trust-badges'],
  }),
  createGuide({
    chapter: 'Home Components',
    chapterOrder: 3,
    section: 'Component theo loại',
    sectionOrder: 2,
    subsection: 'Sản phẩm & dịch vụ',
    subsectionOrder: 3,
    slug: 'admin-home-components-product-service',
    title: 'Product list, grid, categories và service list',
    description: 'Khung nhóm component hiển thị sản phẩm, category và dịch vụ trên homepage.',
    keywords: ['product list', 'product grid', 'service list', 'category products'],
    relatedRoutes: [
      '/admin/home-components/create/product-list',
      '/admin/home-components/create/product-grid',
      '/admin/home-components/create/product-categories',
      '/admin/home-components/create/service-list',
      '/admin/home-components/create/services',
    ],
  }),
  createGuide({
    chapter: 'Home Components',
    chapterOrder: 3,
    section: 'Component theo loại',
    sectionOrder: 2,
    subsection: 'Social proof & content',
    subsectionOrder: 4,
    slug: 'admin-home-components-social-proof',
    title: 'Testimonials, banner ảnh thương hiệu, partners, blog, FAQ',
    description: 'Khung nhóm component social proof, banner ảnh, đối tác, nội dung và FAQ.',
    keywords: ['testimonials', 'banner ảnh thương hiệu', 'clients', 'partners', 'blog', 'faq'],
    relatedRoutes: [
      '/admin/home-components/create/testimonials',
      '/admin/home-components/create/clients',
      '/admin/home-components/create/partners',
      '/admin/home-components/create/blog',
      '/admin/home-components/create/faq',
    ],
  }),
  createGuide({
    chapter: 'Experiences',
    chapterOrder: 4,
    section: 'Content experiences',
    sectionOrder: 1,
    subsection: 'Posts',
    subsectionOrder: 1,
    slug: 'experience-posts',
    title: 'Posts list và posts detail',
    description: 'Khung cấu hình experience cho danh sách bài viết và chi tiết bài viết.',
    keywords: ['posts-list', 'posts-detail', 'experience posts'],
    relatedRoutes: ['/system/experiences/posts-list', '/system/experiences/posts-detail'],
  }),
  createGuide({
    chapter: 'Experiences',
    chapterOrder: 4,
    section: 'Commerce experiences',
    sectionOrder: 2,
    subsection: 'Products & cart',
    subsectionOrder: 1,
    slug: 'experience-products-cart-checkout',
    title: 'Products list, product detail, cart, checkout',
    description: 'Khung commerce experience từ list sản phẩm đến giỏ hàng và checkout.',
    keywords: ['products-list', 'product-detail', 'cart', 'checkout'],
    relatedRoutes: [
      '/system/experiences/products-list',
      '/system/experiences/product-detail',
      '/system/experiences/cart',
      '/system/experiences/checkout',
    ],
  }),
  createGuide({
    chapter: 'Experiences',
    chapterOrder: 4,
    section: 'Commerce experiences',
    sectionOrder: 2,
    subsection: 'Wishlist & promotions',
    subsectionOrder: 2,
    slug: 'experience-wishlist-promotions',
    title: 'Wishlist và promotions list',
    description: 'Khung các màn yêu thích, voucher và khuyến mãi ngoài site.',
    keywords: ['wishlist', 'promotions', 'voucher'],
    relatedRoutes: ['/system/experiences/wishlist', '/system/experiences/promotions-list'],
  }),
  createGuide({
    chapter: 'Experiences',
    chapterOrder: 4,
    section: 'Service & account experiences',
    sectionOrder: 3,
    subsection: 'Services & booking',
    subsectionOrder: 1,
    slug: 'experience-services-booking',
    title: 'Services list, services detail và booking',
    description: 'Khung experience cho dịch vụ, chi tiết dịch vụ và flow đặt lịch.',
    keywords: ['services-list', 'services-detail', 'booking'],
    relatedRoutes: [
      '/system/experiences/services-list',
      '/system/experiences/services-detail',
      '/system/experiences/booking',
    ],
  }),
  createGuide({
    chapter: 'Experiences',
    chapterOrder: 4,
    section: 'Service & account experiences',
    sectionOrder: 3,
    subsection: 'Account & support',
    subsectionOrder: 2,
    slug: 'experience-account-contact-comments',
    title: 'Account profile, account orders, contact, comments',
    description: 'Khung nhóm account/support experiences và các bề mặt tương tác người dùng.',
    keywords: ['account', 'contact', 'comments-rating'],
    relatedRoutes: [
      '/system/experiences/account-profile',
      '/system/experiences/account-orders',
      '/system/experiences/contact',
      '/system/experiences/comments-rating',
    ],
  }),
  createGuide({
    chapter: 'Experiences',
    chapterOrder: 4,
    section: 'Shell & navigation',
    sectionOrder: 4,
    subsection: 'Menu & error pages',
    subsectionOrder: 1,
    slug: 'experience-menu-error-pages',
    title: 'Header menu và error pages',
    description: 'Khung menu experience, shell điều hướng và nhóm trang lỗi hệ thống.',
    keywords: ['menu', 'header menu', 'error pages'],
    relatedRoutes: ['/system/experiences/menu', '/system/experiences/error-pages'],
  }),
  createGuide({
    chapter: 'Seed & Data',
    chapterOrder: 5,
    section: 'Seed workflows',
    sectionOrder: 1,
    subsection: 'Seed wizard',
    subsectionOrder: 1,
    slug: 'seed-wizard-overview',
    title: 'Seed wizard và preset dữ liệu',
    description: 'Khung seed wizard, preset ngành và cách khởi tạo dữ liệu mẫu.',
    keywords: ['seed', 'seed wizard', 'preset'],
    relatedRoutes: ['/system/data'],
  }),
  createGuide({
    chapter: 'Seed & Data',
    chapterOrder: 5,
    section: 'Seed workflows',
    sectionOrder: 1,
    subsection: 'Migration bundles',
    subsectionOrder: 2,
    slug: 'seed-migration-bundles',
    title: 'Migration bundle và import export',
    description: 'Khung migration bundle, import/export và dữ liệu chuyển môi trường.',
    keywords: ['migration bundle', 'import export', 'data migration'],
    relatedRoutes: ['/system/data'],
  }),
  createGuide({
    chapter: 'Seed & Data',
    chapterOrder: 5,
    section: 'Data maintenance',
    sectionOrder: 2,
    subsection: 'Trust pages & reviews',
    subsectionOrder: 1,
    slug: 'admin-trust-pages-reviews',
    title: 'Trust pages và reviews',
    description: 'Khung quản lý trust pages, reviews và bề mặt tăng trust cho site.',
    keywords: ['trust pages', 'reviews', 'uy tín'],
    relatedRoutes: ['/admin/trust-pages', '/admin/reviews'],
  }),
] as const satisfies readonly GuideArticle[];

export const guideArticleMap = new Map(guideArticles.map((article) => [article.slug, article]));

export const searchGuideArticles = (query: string) => {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return guideArticles;
  }

  return guideArticles.filter((article) => {
    const haystack = [
      article.title,
      article.description,
      article.slug,
      article.chapter,
      article.section,
      article.subsection,
      ...article.keywords,
      ...article.relatedRoutes,
    ]
      .join(' ')
      .toLowerCase();

    return haystack.includes(normalized);
  });
};

export const guideTree = guideArticles.reduce<
  Array<{
    chapter: string;
    items: Array<{
      section: string;
      items: Array<{
        subsection: string;
        items: GuideArticle[];
      }>;
    }>;
  }>
>((chapters, article) => {
  let chapter = chapters.find((entry) => entry.chapter === article.chapter);
  if (!chapter) {
    chapter = { chapter: article.chapter, items: [] };
    chapters.push(chapter);
  }

  let section = chapter.items.find((entry) => entry.section === article.section);
  if (!section) {
    section = { section: article.section, items: [] };
    chapter.items.push(section);
  }

  let subsection = section.items.find((entry) => entry.subsection === article.subsection);
  if (!subsection) {
    subsection = { subsection: article.subsection, items: [] };
    section.items.push(subsection);
  }

  subsection.items.push(article);
  return chapters;
}, []);
